apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quarkus-app
  annotations:
    github.com/project-slug: nwiremint/quarkus-app
    argocd/app-name: quarkus-app
spec:
  type: other
  lifecycle: development
  owner: user:default/guest
