apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-read-run
spec:
  pipelineRef:
    name: clone-read
  workspaces:
  - name: maven-settings
    emptyDir: {}
  - name: shared-data
    persistentvolumeclaim:
        claimName: shared-data
  - name: maven-local-m2
    persistentvolumeclaim:
        claimName: shared-data
  - name: git-credentials
    secret:
      secretName: git-credentials
  - name: docker-credentials
    secret:
      secretName: dockercred                
  params:
    - name: repo-url
      value: https://github.com/rajat965ng/quarkus-app
    - name: image-reference
      value: default-route-openshift-image-registry.apps-crc.testing/quarkus/codewithquarkus
    - name: registry
      value: default-route-openshift-image-registry.apps-crc.testing  
